### ISSUE TITLE
url_fetcher does not work with Python 3.9, weasyprint 53.4

### ISSUE THREAD

**Issue by StuartLittlefair** [Kozea/Flask-WeasyPrint#28]
I'm using weasyprint version 53.4 and the latest pip installable version of flask-weasyprint. Python 3.9. Here is a minimal working example of the problem:

```python
from flask import url_for
from flask_weasyprint import CSS

url = url_for('static', filename='pdfstyle.css')
css = CSS(url)
```

The url_fetcher logic seems to be broken in this instance since it generates the following error:

```
weasyprint.urls.URLFetchingError: ValueError: Flask-WeasyPrint got HTTP status 403 FORBIDDEN for https://127.0.0.1:5000b'/static/pdfstyle.css'
```

Notice the conversion of the filename to a bytes object....

**Comment by liZe** [comment]
Hello!

> Notice the conversion of the filename to a bytes object....

The bytestring/unicode problem is in the error message, not in the logic. We should fix this, but the problem you have is not caused by this error.

You actually get a 403 error when you try to retrieve `https://127.0.0.1:5000/static/pdfstyle.css` using Flask’s test client (that’s used by Flask-WeasyPrint’s URL fetcher). Static files are generally handled by Flask’s [send_static_file](https://flask.palletsprojects.com/en/2.0.x/api/?highlight=send_static_file#flask.Flask.send_static_file), that doesn’t return 403 errors as far as I can tell.

So, it means that your application is probably overriding the `static` route somewhere, with a route that returns a 403 error when used with Flask’s client. In this case, you’ll have to use your own URL fetcher to bypass rights management.

**Comment by StuartLittlefair** [comment]
Thank you! And apologies for raising a false issue. 

Your explanation helped me find my issue. For anyone else who stumbles across this, the URL fetcher was being blocked by rules I have in my flask app limiting the allowed IPs. The client used to access the CSS file has an IP of `'None'`

**Comment by liZe** [comment]
> And apologies for raising a false issue.

No problem! We’ve fixed the error message thanks to your report.
